cls
powershell -file TEstExecuteNonQueryAlterSPMultiplesIntancias.ps1
powershell -file TestGetQueryMultipleServersOutputHtml.ps1
powershell -file TestGetCommand.ps1
powershell -file Test_GetSqlValue_Getdate.ps1
